<?php
declare(strict_types=1); require_once __DIR__.'/../includes/layout.php'; require_admin();
$stats=db()->query("SELECT (SELECT COUNT(*) FROM books) total,(SELECT COUNT(*) FROM books WHERE status='available') available,(SELECT COUNT(*) FROM reservations WHERE status='pending') pending,(SELECT COUNT(*) FROM reservations WHERE status='approved') waiting,(SELECT COUNT(*) FROM rentals WHERE status='borrowed') borrowed,(SELECT COUNT(*) FROM rentals WHERE status='borrowed' AND due_date<CURDATE()) overdue")->fetch();
$overdue=db()->query("SELECT r.*,b.title,COALESCE(u.fullname,r.walkin_name) customer,DATEDIFF(CURDATE(),r.due_date) overdue_days FROM rentals r JOIN books b ON b.id=r.book_id LEFT JOIN users u ON u.id=r.user_id WHERE r.status='borrowed' AND r.due_date<CURDATE() ORDER BY r.due_date")->fetchAll();
$latest=db()->query("SELECT rs.*,u.fullname,b.title FROM reservations rs JOIN users u ON u.id=rs.user_id JOIN books b ON b.id=rs.book_id ORDER BY rs.created_at DESC LIMIT 6")->fetchAll();
page_start('ภาพรวมร้าน','dashboard'); ?>
<div class="page-head"><div><h1>ภาพรวมร้าน</h1><p>ติดตามหนังสือ การจอง และรายการที่ต้องดำเนินการ</p></div></div>
<?php if($overdue): $max=max(array_column($overdue,'overdue_days'));$fine=array_sum(array_map(fn($r)=>(int)$r['overdue_days']*10,$overdue));?><section class="alert-overdue"><strong><?=count($overdue)?> รายการเกินกำหนด</strong><span>สูงสุด <?=e($max)?> วัน · ค่าปรับประมาณ <?=format_money($fine)?> บาท</span></section><?php endif?>
<section class="cards"><?php foreach([['หนังสือทั้งหมด',$stats['total']],['พร้อมให้เช่า',$stats['available']],['จองรอตรวจสอบ',$stats['pending']],['รอลูกค้ามารับ',$stats['waiting']],['กำลังถูกยืม',$stats['borrowed']],['เกินกำหนด',$stats['overdue']]] as $s):?><article class="stat"><small><?=e($s[0])?></small><b><?=e($s[1])?></b></article><?php endforeach?></section>
<?php if($overdue):?><section class="panel"><div class="panel-head"><h2>รายการเกินกำหนด</h2><a class="btn" href="returns.php">จัดการคืนหนังสือ</a></div><div class="table-wrap"><table><thead><tr><th>ลูกค้า</th><th>หนังสือ</th><th>กำหนดคืน</th><th>เกินกำหนด</th><th>ค่าปรับโดยประมาณ</th></tr></thead><tbody><?php foreach($overdue as $r):?><tr class="overdue"><td><?=e($r['customer'])?></td><td><?=e($r['title'])?></td><td><?=thai_date($r['due_date'])?></td><td><?=e($r['overdue_days'])?> วัน</td><td class="money"><?=format_money((int)$r['overdue_days']*10)?> บาท</td></tr><?php endforeach?></tbody></table></div></section><?php endif?>
<section class="panel"><div class="panel-head"><h2>รายการจองล่าสุด</h2><a class="btn" href="reservations.php">ดูทั้งหมด</a></div><div class="table-wrap"><table><thead><tr><th>สมาชิก</th><th>หนังสือ</th><th>วันรับ</th><th>สร้างเมื่อ</th><th>สถานะ</th></tr></thead><tbody><?php foreach($latest as $r):?><tr><td><?=e($r['fullname'])?></td><td><?=e($r['title'])?></td><td><?=thai_date($r['pickup_date'])?></td><td><?=thai_date($r['created_at'],true)?></td><td><?=status_badge($r['status'],reservation_label($r['status']))?></td></tr><?php endforeach?><?php if(!$latest):?><tr><td colspan="5" class="empty">ยังไม่มีรายการจอง</td></tr><?php endif?></tbody></table></div></section>
<?php page_end(); ?>


