<?php
declare(strict_types=1); require_once __DIR__.'/../includes/layout.php'; require_member();
$q=trim((string)($_GET['q']??''));$cat=(int)($_GET['category']??0);$sql='SELECT b.*,c.name category FROM books b JOIN categories c ON c.id=b.category_id WHERE (b.title LIKE ? OR b.author LIKE ?)';$args=["%$q%","%$q%"];$sql.=$cat?' AND b.category_id=?':'';if($cat)$args[]=$cat;$sql.=' ORDER BY b.created_at DESC';$s=db()->prepare($sql);$s->execute($args);$books=$s->fetchAll();$cats=db()->query('SELECT * FROM categories ORDER BY name')->fetchAll();$today=date('Y-m-d');$tomorrow=date('Y-m-d',strtotime('+1 day'));
page_start('ร้านหนังสือ','store'); ?>
<div class="page-head"><div><h1>ค้นพบหนังสือเล่มถัดไป</h1><p>เลือกอ่านรายละเอียดและจองหนังสือเพื่อมารับที่ร้าน</p></div></div>
<form class="filters"><input name="q" value="<?=e($q)?>" placeholder="ค้นหาชื่อหนังสือหรือผู้แต่ง"><select name="category"><option value="0">ทุกหมวดหมู่</option><?php foreach($cats as $c):?><option value="<?=$c['id']?>" <?=$cat==$c['id']?'selected':''?>><?=e($c['name'])?></option><?php endforeach?></select><button class="btn btn-primary">ค้นหา</button></form>
<section class="book-grid"><?php foreach($books as $b):?><article class="book-card"><div class="cover"><?php if($b['cover_image']):?><img src="<?=base_url($b['cover_image'])?>" alt="ปก <?=e($b['title'])?>"><?php else:?><div class="cover-placeholder"><?=e($b['title'])?></div><?php endif?></div><div class="book-body"><?=status_badge($b['status'],book_status_label($b['status']))?><h3><?=e($b['title'])?></h3><p><?=e($b['author'])?> · <?=e($b['category'])?></p><div class="book-meta"><span class="money"><?=number_format($b['rental_price_per_day'],2)?> ฿/วัน</span></div><div class="book-actions"><button class="btn" data-modal-open="detail<?=$b['id']?>">รายละเอียด</button><button class="btn btn-primary" data-modal-open="reserve<?=$b['id']?>" <?=$b['status']!=='available'?'disabled':''?>>จองหนังสือ</button></div></div></article>
<dialog id="detail<?=$b['id']?>"><div class="modal-head"><h2><?=e($b['title'])?></h2><button data-modal-close>×</button></div><div class="modal-body form-grid"><div class="cover"><?php if($b['cover_image']):?><img src="<?=base_url($b['cover_image'])?>" alt=""><?php else:?><div class="cover-placeholder"><?=e($b['title'])?></div><?php endif?></div><div><p><b>ผู้แต่ง:</b> <?=e($b['author'])?></p><p><b>หมวดหมู่:</b> <?=e($b['category'])?></p><p><b>ISBN:</b> <?=e($b['isbn']?:'-')?></p><p><b>สำนักพิมพ์:</b> <?=e($b['publisher']?:'-')?></p><p><b>ปีที่พิมพ์:</b> <?=e($b['publication_year']?:'-')?></p><p><b>ค่าเช่า:</b> <?=number_format($b['rental_price_per_day'],2)?> บาท/วัน</p><?=status_badge($b['status'],book_status_label($b['status']))?><p><?=nl2br(e($b['description']?:'ยังไม่มีเรื่องย่อ'))?></p><?php if($b['status']==='available'):?><button class="btn btn-primary" data-modal-open="reserve<?=$b['id']?>" onclick="this.closest('dialog').close()">จองหนังสือเล่มนี้</button><?php endif?></div></div></dialog>
<dialog id="reserve<?=$b['id']?>"><div class="modal-head"><h2>จอง “<?=e($b['title'])?>”</h2><button data-modal-close>×</button></div><form class="modal-body" method="post" action="<?=base_url('actions/reserve.php')?>"><?=csrf_field()?><input type="hidden" name="book_id" value="<?=$b['id']?>"><label class="field">เลือกวันรับหนังสือ</label><div class="options two" data-option-group><input type="hidden" name="pickup_date" value="<?=$today?>"><button type="button" class="option selected" data-value="<?=$today?>"><b>วันนี้</b><small><?=thai_date($today)?></small></button><button type="button" class="option" data-value="<?=$tomorrow?>"><b>พรุ่งนี้</b><small><?=thai_date($tomorrow)?></small></button></div><label class="field" style="margin-top:15px">ระยะเวลาเช่า</label><div class="options" data-option-group><input type="hidden" name="rental_days" value="3"><button type="button" class="option selected" data-value="3"><b>3 วัน</b></button><button type="button" class="option" data-value="7"><b>7 วัน</b></button><button type="button" class="option" data-value="14"><b>14 วัน</b></button></div><div class="rental-calc" data-rental-calc></div><button class="btn btn-primary">ยืนยันการจอง</button></form></dialog><?php endforeach?><?php if(!$books):?><div class="empty">ไม่พบหนังสือที่ค้นหา</div><?php endif?></section>
<?php page_end(); ?>
