<?php
declare(strict_types=1); require_once __DIR__.'/../includes/layout.php'; require_member();$uid=current_user()['id'];
$s=db()->prepare('SELECT rs.*,b.title,b.cover_image FROM reservations rs JOIN books b ON b.id=rs.book_id WHERE rs.user_id=? ORDER BY rs.created_at DESC');$s->execute([$uid]);$reservations=$s->fetchAll();$s=db()->prepare('SELECT r.*,b.title FROM rentals r JOIN books b ON b.id=r.book_id WHERE r.user_id=? ORDER BY r.created_at DESC');$s->execute([$uid]);$rentals=$s->fetchAll();$counts=['pending'=>0,'approved'=>0,'borrowed'=>0];foreach($reservations as $r)if(isset($counts[$r['status']]))$counts[$r['status']]++;foreach($rentals as $r)if($r['status']==='borrowed')$counts['borrowed']++;
page_start('การจองและการเช่าของฉัน','mine'); ?>
<div class="page-head"><div><h1>การจอง / การเช่าของฉัน</h1><p>ติดตามคำขอ วันรับหนังสือ และประวัติการเช่า</p></div></div><section class="cards" style="grid-template-columns:repeat(3,1fr)"><article class="stat"><small>รอตรวจสอบ</small><b><?=$counts['pending']?></b></article><article class="stat"><small>รอรับหนังสือ</small><b><?=$counts['approved']?></b></article><article class="stat"><small>กำลังยืม</small><b><?=$counts['borrowed']?></b></article></section>
<section class="panel"><div class="panel-head"><h2>รายการจอง</h2></div><div class="table-wrap"><table><thead><tr><th>หนังสือ</th><th>วันรับ</th><th>กำหนดคืน</th><th>สร้างเมื่อ</th><th>สถานะ</th></tr></thead><tbody><?php foreach($reservations as $r):?><tr><td><?=e($r['title'])?></td><td><?=thai_date($r['pickup_date'])?></td><td><?=thai_date($r['due_date'])?></td><td><?=thai_date($r['created_at'],true)?></td><td><?=status_badge($r['status'],reservation_label($r['status']))?></td></tr><?php endforeach?><?php if(!$reservations):?><tr><td colspan="5" class="empty">ยังไม่มีการจอง</td></tr><?php endif?></tbody></table></div></section>
<section class="panel"><div class="panel-head"><h2>ประวัติการเช่า</h2></div><div class="table-wrap"><table><thead><tr><th>หนังสือ</th><th>เริ่มเช่า</th><th>กำหนดคืน</th><th>คืนจริง</th><th>ค่าเช่า</th><th>ค่าปรับ</th><th>สถานะ</th></tr></thead><tbody><?php foreach($rentals as $r):?><tr><td><?=e($r['title'])?></td><td><?=thai_date($r['borrowed_at'],true)?></td><td><?=thai_date($r['due_date'])?></td><td><?=thai_date($r['returned_at'],true)?></td><td><?=format_money($r['rental_total'])?></td><td><?=format_money($r['fine'])?></td><td><?=status_badge($r['status'],rental_label($r['status']))?></td></tr><?php endforeach?><?php if(!$rentals):?><tr><td colspan="7" class="empty">ยังไม่มีประวัติการเช่า</td></tr><?php endif?></tbody></table></div></section>
<?php page_end(); ?>

